//
//  DVAutoGeneratedProperties.h
//  DVAutoGeneratedProperties
//
//  Created by Vladislav Dugnist on 03/03/2018.
//

#import <Foundation/Foundation.h>

typedef void (^dvClassPropertySetterBlock)(id blockSelf, id value);
typedef id (^dvClassPropertyGetterBlock)(id blockSelf);

@interface DVAutoGeneratedProperties : NSObject

+ (dvClassPropertySetterBlock)setterBlockForGetterSelector:(SEL)getterSelector;
+ (dvClassPropertyGetterBlock)getterBlockForSelector:(SEL)getterSelector;

@end
