//
//  DVAutoGeneratedProperties.m
//  DVAutoGeneratedProperties
//
//  Created by Vladislav Dugnist on 03/03/2018.
//

#import "DVAutoGeneratedProperties.h"
#import "DVAutoGeneratedPropertiesHelpers.h"
#import <objc/runtime.h>

@implementation DVAutoGeneratedProperties

+ (BOOL)resolveClassMethod:(SEL)sel {
    if (!sel_isGetterOrSetter(sel)) {
        return NO;
    }
    
    objc_property_t property = classPropertyForSelector(self, sel);
    
    if (sel_isSetter(sel)) {
        SEL getterSel = sel_getterFromSetter(sel);
        dvClassPropertySetterBlock setterBlock = [self setterBlockForGetterSelector:getterSel];
        IMP blockImplementation = imp_implementationWithBlock(setterBlock);
        char *methodTypes = copySetterMethodTypesForProperty(property);
        assert(class_addMethod(object_getClass(self), sel, blockImplementation, methodTypes));
        free(methodTypes);
    }
    else {
        dvClassPropertyGetterBlock getterBlock = [self getterBlockForSelector:sel];
        IMP blockImplementation = imp_implementationWithBlock(getterBlock);
        char *methodTypes = copyGetterMethodTypesForProperty(property);
        assert(class_addMethod(object_getClass(self), sel, blockImplementation, methodTypes));
        free(methodTypes);
    }
    
    return YES;
}

+ (dvClassPropertySetterBlock)setterBlockForGetterSelector:(SEL)getterSelector {
    @throw @"Override this method in subclass";
}

+ (dvClassPropertyGetterBlock)getterBlockForSelector:(SEL)getterSelector {
    @throw @"Override this method in subclass";
}

@end
