//
//  DVAutoGeneratedProperties.m
//  DVAutoGeneratedProperties
//
//  Created by Vladislav Dugnist on 03/03/2018.
//

#import "DVAutoGeneratedProperties.h"
#import "DVAutoGeneratedPropertiesHelpers.h"
#import <objc/runtime.h>

@implementation DVAutoGeneratedProperties

+ (BOOL)resolveClassMethod:(SEL)sel {
    return [self resolveMethodFor:object_getClass(self) selector:sel];
}

+ (BOOL)resolveInstanceMethod:(SEL)sel {
    return [self resolveMethodFor:self selector:sel];
}

+ (BOOL)resolveMethodFor:(id)target selector:(SEL)sel {
    if (!sel_isGetterOrSetter(target, sel)) {
        return NO;
    }
    
    objc_property_t property = propertyForSelector(target, sel);
    
    if (sel_isSetter(target, sel)) {
        SEL getterSel = sel_getterFromSetter(sel);
        dvPropertySetterBlock setterBlock = [self setterBlockForTarget:target getterSelector:getterSel];
        IMP blockImplementation = imp_implementationWithBlock(setterBlock);
        char *methodTypes = copySetterMethodTypesForProperty(property);
        assert(class_addMethod(target, sel, blockImplementation, methodTypes));
        free(methodTypes);
    }
    else {
        dvPropertyGetterBlock getterBlock = [self getterBlockForTarget:target getterSelector:sel];
        IMP blockImplementation = imp_implementationWithBlock(getterBlock);
        char *methodTypes = copyGetterMethodTypesForProperty(property);
        assert(class_addMethod(target, sel, blockImplementation, methodTypes));
        free(methodTypes);
    }
    
    return YES;
}

+ (dvPropertySetterBlock)setterBlockForTarget:(id)target getterSelector:(SEL)getterSelector {
    @throw @"Override this method in subclass";
}

+ (dvPropertyGetterBlock)getterBlockForTarget:(id)target getterSelector:(SEL)getterSelector {
    @throw @"Override this method in subclass";
}

@end
