//
//  DVAppDelegate.h
//  DVAutoGeneratedProperties
//
//  Created by vdugnist on 03/03/2018.
//  Copyright (c) 2018 vdugnist. All rights reserved.
//

@import UIKit;

@interface DVAppDelegate : UIResponder <UIApplicationDelegate>

@property (strong, nonatomic) UIWindow *window;

@end
