//
//  DVUserDefaults.m
//  DVAutoGeneratedProperties_Example
//
//  Created by Vladislav Dugnist on 04/03/2018.
//  Copyright © 2018 vdugnist. All rights reserved.
//

#import "DVUserDefaults.h"

@implementation DVUserDefaults

@dynamic savedText;

+ (dvClassPropertySetterBlock)setterBlockForGetterSelector:(SEL)getterSelector {
    return ^(id blockSelf, id value) {
        [[NSUserDefaults standardUserDefaults] setObject:value forKey:NSStringFromSelector(getterSelector)];
    };
}

+ (dvClassPropertyGetterBlock)getterBlockForSelector:(SEL)getterSelector {
    return ^id(id blockSelf) {
        return [[NSUserDefaults standardUserDefaults] objectForKey:NSStringFromSelector(getterSelector)];
    };
}

@end
