//
//  DVUserDefaults.h
//  DVAutoGeneratedProperties_Example
//
//  Created by Vladislav Dugnist on 04/03/2018.
//  Copyright © 2018 vdugnist. All rights reserved.
//

#import <DVAutoGeneratedProperties/DVAutoGeneratedProperties.h>

@interface DVUserDefaults : DVAutoGeneratedProperties

@property (class) NSString *savedText;

@end
