//
//  DVViewController.m
//  DVAutoGeneratedProperties
//
//  Created by vdugnist on 03/03/2018.
//  Copyright (c) 2018 vdugnist. All rights reserved.
//

#import "DVViewController.h"
#import "DVUserDefaults.h"

@interface DVViewController () <UITextFieldDelegate>

@property (weak, nonatomic) IBOutlet UILabel *label;
@property (weak, nonatomic) IBOutlet UITextField *textField;

@end

@implementation DVViewController

- (void)viewDidLoad
{
    [super viewDidLoad];
    [self updateLabelText];
    self.textField.delegate = self;
    
}

- (BOOL)textFieldShouldReturn:(UITextField *)textField {
    [textField endEditing:YES];
    
    DVUserDefaults.savedText = textField.text;
    textField.text = nil;
    [self updateLabelText];
    
    return YES;
}

- (void)updateLabelText {
    NSMutableString *labelText = [@"Stored value: " mutableCopy];
    
    if (DVUserDefaults.savedText) {
        [labelText appendString:DVUserDefaults.savedText];
    }
    
    self.label.text = labelText;
}

@end
