//
//  main.m
//  DVAutoGeneratedProperties
//
//  Created by vdugnist on 03/03/2018.
//  Copyright (c) 2018 vdugnist. All rights reserved.
//

@import UIKit;
#import "DVAppDelegate.h"

int main(int argc, char * argv[])
{
    @autoreleasepool {
        return UIApplicationMain(argc, argv, nil, NSStringFromClass([DVAppDelegate class]));
    }
}
