//
//  DVAutoGeneratedPropertiesTests.m
//  DVAutoGeneratedPropertiesTests
//
//  Created by vdugnist on 03/03/2018.
//  Copyright (c) 2018 vdugnist. All rights reserved.
//

#import "DVAutoSynthesizedProperties.h"

@interface DVTestAutoSythesizedClassProperties : DVAutoSynthesizedProperties

@property (class) NSString *testString;
@property (class, weak) NSString *testWeakProperty;
@property (class, copy) NSString *testCopyProperty;

@end

@implementation DVTestAutoSythesizedClassProperties

@dynamic testString;
@dynamic testWeakProperty;
@dynamic testCopyProperty;

@end

@import XCTest;

@interface ClassPropertiesTests : XCTestCase

@end

@implementation ClassPropertiesTests

- (void)testAutoGeneratedStrongProperty {
    DVTestAutoSythesizedClassProperties.testString = nil;
    XCTAssertNil(DVTestAutoSythesizedClassProperties.testString);
    
    NSString *testString = [@"hello" stringByAppendingString:@" world"];
    CFIndex retainCountBeforeAssign = CFGetRetainCount((__bridge CFTypeRef)testString);
    DVTestAutoSythesizedClassProperties.testString = testString;
    XCTAssertNotEqual(retainCountBeforeAssign, CFGetRetainCount((__bridge CFTypeRef)testString));
    XCTAssertEqual(testString, DVTestAutoSythesizedClassProperties.testString);
}

- (void)testAutoGeneratedWeakProperty {
    DVTestAutoSythesizedClassProperties.testWeakProperty = nil;
    XCTAssertNil(DVTestAutoSythesizedClassProperties.testWeakProperty);
    
    NSString *testString = [@"hello" stringByAppendingString:@" world"];
    CFIndex retainCountBeforeAssign = CFGetRetainCount((__bridge CFTypeRef)testString);
    DVTestAutoSythesizedClassProperties.testWeakProperty = testString;
    XCTAssertEqual(retainCountBeforeAssign, CFGetRetainCount((__bridge CFTypeRef)testString));
    XCTAssertEqual(testString, DVTestAutoSythesizedClassProperties.testWeakProperty);
}

- (void)testAutoGeneratedCopyProperty {
    DVTestAutoSythesizedClassProperties.testCopyProperty = nil;
    XCTAssertNil(DVTestAutoSythesizedClassProperties.testCopyProperty);
    
    NSMutableString *testString = [NSMutableString stringWithString:@"hello world"];
    DVTestAutoSythesizedClassProperties.testCopyProperty = testString;
    XCTAssertEqualObjects(testString, DVTestAutoSythesizedClassProperties.testCopyProperty);
    XCTAssertNotEqual(testString, DVTestAutoSythesizedClassProperties.testCopyProperty);
}

@end

