//
//  DVAutoSynthesizedProperties.h
//  DVAutoGeneratedProperties_Tests
//
//  Created by Vladislav Dugnist on 04/03/2018.
//  Copyright © 2018 vdugnist. All rights reserved.
//

#import <DVAutoGeneratedProperties.h>

@interface DVAutoSynthesizedProperties : DVAutoGeneratedProperties

@end
