//
//  InstancePropertiesTests.m
//  DVAutoGeneratedProperties_Tests
//
//  Created by Vladislav Dugnist on 18/03/2018.
//  Copyright © 2018 vdugnist. All rights reserved.
//

#import <XCTest/XCTest.h>
#import "DVAutoSynthesizedProperties.h"

@interface DVTestAutoSythesizedInstanceProperties : DVAutoSynthesizedProperties

@property (nonatomic) NSString *testString;
@property (nonatomic, weak) NSString *testWeakProperty;
@property (nonatomic, copy) NSString *testCopyProperty;

@end

@implementation DVTestAutoSythesizedInstanceProperties

@dynamic testString;
@dynamic testWeakProperty;
@dynamic testCopyProperty;

@end

@interface InstancePropertiesTests : XCTestCase

@property (nonatomic) DVTestAutoSythesizedInstanceProperties *testObj;

@end

@implementation InstancePropertiesTests

- (void)setUp {
    self.testObj = [DVTestAutoSythesizedInstanceProperties new];
}

- (void)testAutoGeneratedStrongProperty {
    self.testObj.testString = nil;
    XCTAssertNil(self.testObj.testString);
    
    NSString *testString = [@"hello" stringByAppendingString:@" world"];
    CFIndex retainCountBeforeAssign = CFGetRetainCount((__bridge CFTypeRef)testString);
    self.testObj.testString = testString;
    XCTAssertNotEqual(retainCountBeforeAssign, CFGetRetainCount((__bridge CFTypeRef)testString));
    XCTAssertEqual(testString, self.testObj.testString);
}

- (void)testAutoGeneratedWeakProperty {
    self.testObj.testWeakProperty = nil;
    XCTAssertNil(self.testObj.testWeakProperty);
    
    NSString *testString = [@"hello" stringByAppendingString:@" world"];
    CFIndex retainCountBeforeAssign = CFGetRetainCount((__bridge CFTypeRef)testString);
    self.testObj.testWeakProperty = testString;
    XCTAssertEqual(retainCountBeforeAssign, CFGetRetainCount((__bridge CFTypeRef)testString));
    XCTAssertEqual(testString, self.testObj.testWeakProperty);
}

- (void)testAutoGeneratedCopyProperty {
    self.testObj.testCopyProperty = nil;
    XCTAssertNil(self.testObj.testCopyProperty);
    
    NSMutableString *testString = [NSMutableString stringWithString:@"hello world"];
    self.testObj.testCopyProperty = testString;
    XCTAssertEqualObjects(testString, self.testObj.testCopyProperty);
    XCTAssertNotEqual(testString, self.testObj.testCopyProperty);
}

@end
