//
//  DVAutoGeneratedPropertiesTests.m
//  DVAutoGeneratedPropertiesTests
//
//  Created by vdugnist on 03/03/2018.
//  Copyright (c) 2018 vdugnist. All rights reserved.
//

#import "DVAutoSynthesizedProperties.h"

@interface DVTestAutoSythesizedProperties : DVAutoSynthesizedProperties

@property (class) NSString *testString;
@property (class, weak) NSString *testWeakProperty;
@property (class, copy) NSString *testCopyProperty;

@end

@implementation DVTestAutoSythesizedProperties

@dynamic testString;
@dynamic testWeakProperty;
@dynamic testCopyProperty;

@end

@import XCTest;

@interface Tests : XCTestCase

@end

@implementation Tests

- (void)testAutoGeneratedStrongProperty {
    DVTestAutoSythesizedProperties.testString = nil;
    XCTAssertNil(DVTestAutoSythesizedProperties.testString);
    
    NSString *testString = [@"hello" stringByAppendingString:@" world"];
    CFIndex retainCountBeforeAssign = CFGetRetainCount((__bridge CFTypeRef)testString);
    DVTestAutoSythesizedProperties.testString = testString;
    XCTAssertNotEqual(retainCountBeforeAssign, CFGetRetainCount((__bridge CFTypeRef)testString));
    XCTAssertEqual(testString, DVTestAutoSythesizedProperties.testString);
}

- (void)testAutoGeneratedWeakProperty {
    DVTestAutoSythesizedProperties.testWeakProperty = nil;
    XCTAssertNil(DVTestAutoSythesizedProperties.testWeakProperty);
    
    NSString *testString = [@"hello" stringByAppendingString:@" world"];
    CFIndex retainCountBeforeAssign = CFGetRetainCount((__bridge CFTypeRef)testString);
    DVTestAutoSythesizedProperties.testWeakProperty = testString;
    XCTAssertEqual(retainCountBeforeAssign, CFGetRetainCount((__bridge CFTypeRef)testString));
    XCTAssertEqual(testString, DVTestAutoSythesizedProperties.testWeakProperty);
}

- (void)testAutoGeneratedCopyProperty {
    DVTestAutoSythesizedProperties.testCopyProperty = nil;
    XCTAssertNil(DVTestAutoSythesizedProperties.testCopyProperty);
    
    NSMutableString *testString = [NSMutableString stringWithString:@"hello world"];
    DVTestAutoSythesizedProperties.testCopyProperty = testString;
    XCTAssertEqualObjects(testString, DVTestAutoSythesizedProperties.testCopyProperty);
    XCTAssertNotEqual(testString, DVTestAutoSythesizedProperties.testCopyProperty);
}

@end

